---
stages:
  - docs
  - deploy

include:
  - project: shared/gitlab/docs-as-gitlab-pages
    ref: main
    file:
      - update-static-docs.yml

update-static-docs:
  only:
  - main

pages:
  only:
  - main
